# Generated by Django 5.1 on 2024-10-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
